#pragma once

/// @file cct.hpp
/// Correlated Color Temperature (CCT) and Duv via the Ohno method.
///
/// Implements the triangular + parabolic search from:
///   Ohno, Y. "Practical Use and Calculation of CCT and Duv."
///   Leukos 10(1):47-55. doi:10.1080/15502724.2014.839020
///   (TM-30-20's reference list dates the article 2013, online-first;
///   the DOI is the stable citation.)
///
/// The Planckian locus is represented as a pre-computed lookup table
/// of (T, u, v) points in CIE 1960 UCS, generated by integrating
/// the Planckian radiator formula with a colour-matching-function set.
/// data/planckian_uv.csv holds the CIE 1931 2-deg table (loaded with
/// load_planckian_lut); build_planckian_lut() generates the same table
/// for any CMF, so the locus can share an observer with the test source.
///
/// TM-30-20 S3.3 prints no CCT algorithm; it incorporates the Ohno
/// method by normative reference. Per TM-30-20 S3.1, CCT determination
/// uses the CIE 1931 2-deg observer.

#include "tm30/reference.hpp"
#include "tm30/resample.hpp"

#include <string>
#include <vector>

namespace tm30 {

/// Result of CCT/Duv computation.
struct CctDuvResult {
  double cct; // Correlated Color Temperature (K)
  double duv; // Signed distance from Planckian locus in CIE 1960 UCS
              // Positive = above (green/yellow), negative = below (pink/purple)
};

/// Pre-computed Planckian locus lookup table.
///
/// Contains (T, u, v) points on the Planckian locus in CIE 1960 UCS,
/// generated with one colorimetric observer (CIE 1931 2-deg for the
/// shipped CSV, see build_planckian_lut() for others).
/// Points are ordered by increasing temperature.
struct PlanckianLut {
  std::vector<double> T; // Temperatures (K), monotonically increasing
  std::vector<double> u; // CIE 1960 UCS u coordinate
  std::vector<double> v; // CIE 1960 UCS v coordinate
  /// Daylight Tr map for the observer this LUT was built with. Empty (the
  /// default, and what load/build_planckian_lut leave) = printed TM-30-20
  /// S3.3 Tr = Tt. Fill with build_daylight_tr_map().
  DaylightTrMap daylight_tr;
};

/// Load a Planckian locus LUT from a CSV file.
///
/// Expected CSV format: cct,u,v  (header row with those column names).
/// @throws std::runtime_error on file-not-found or parse failure.
PlanckianLut load_planckian_lut(const std::string &filepath);

/// Build a Planckian locus LUT at runtime for the given CMF.
///
/// Same construction as tools/generate_planckian_lut.py: T[n] = 1000 *
/// 1.0025^n (n = 0..1488), relative Planck radiance (TM-30-20 S3.3 Eq. (6)),
/// trapezoidal integration over the CMF's own wavelength grid, then CIE 1960
/// UCS (u, v). Use the same CMF that computes the test source's CCT XYZ so
/// source and locus share an observer. With the full-range CIE 1931 2-deg
/// table (data/cmf_1931_2.csv) this reproduces data/planckian_uv.csv to ~1e-15.
/// The locus is integrated over the CMF's own wavelength range, so it depends
/// on that range, not only on the observer (a 380-780 trimmed file gives a
/// slightly different locus than the 360-830 file).
/// @throws std::invalid_argument if the wavelengths are not finite, > 0 and
///   strictly increasing, the CMF does not cover 380-780 nm (TM-30-20 S3.5),
///   or the integration yields a degenerate (u, v).
PlanckianLut build_planckian_lut(const CmfData &cmf);

/// Build the daylight Tr map that makes the CIE daylight reference have
/// CCT == Tt in the observer `cmf`/`lut` were built with.
///
/// For Tr_k = 3000 * 1.0025^k (up to 60000 K) the printed xD/yD/M1/M2
/// daylight SPD is generated on a 380-780 nm, 1 nm grid, integrated with
/// `cmf` and run through the CCT solver with `lut`, giving g_k = CCT of
/// daylight(Tr_k) in that observer. The map is T = g_k -> Tr = Tr_k, so
/// feeding Tr(Tt) to the printed formula yields a daylight SPD of CCT Tt.
/// TM-30-20 S3.5 range; `lut` must come from build_planckian_lut(cmf).
/// @throws std::invalid_argument if g_k is not strictly increasing or does
///   not span at least 4000-25000 K.
DaylightTrMap build_daylight_tr_map(const CmfData &cmf, const PlanckianLut &lut,
                                    const DaylightBasis &basis);

/// Options for the CCT/Duv solver.
struct CctOptions {
  /// Apply the shifted-triangular correction below the |Duv| selection
  /// threshold: T = T_tri + (T_par - T_tri) * |Duv_tri| / threshold.
  ///
  /// luxpy's Ohno implementation documents this refinement as used by the
  /// TM-30 and CQS calculators; it is absent from the published Ohno
  /// (2014) method (and from Smet et al. 2023's description of it), so no
  /// clause applies. It is therefore opt-in and OFF by default; the default
  /// follows the published method exactly.
  bool shifted_triangular_blend = false;
};

/// Compute CCT and Duv from CIE 1960 UCS (u,v) chromaticity.
///
/// Uses the Ohno 2014 triangular + parabolic search algorithm.
/// The LUT must contain at least 3 points covering the expected
/// temperature range of the test source.
///
/// @param u_test  CIE 1960 UCS u coordinate of the test source.
/// @param v_test  CIE 1960 UCS v coordinate of the test source.
/// @param lut     Pre-computed Planckian locus LUT (CIE 1931 2-deg observer).
/// @return        CctDuvResult with CCT (K) and Duv.
CctDuvResult compute_cct_duv(double u_test, double v_test,
                             const PlanckianLut &lut,
                             const CctOptions &options = {});

/// Compute CCT and Duv from CIE 1931 2-deg XYZ tristimulus values.
///
/// Convenience overload that converts XYZ to (u,v) first.
///
/// @param X  CIE 1931 2-deg X tristimulus value.
/// @param Y  CIE 1931 2-deg Y tristimulus value.
/// @param Z  CIE 1931 2-deg Z tristimulus value.
/// @param lut Pre-computed Planckian locus LUT.
/// @return    CctDuvResult with CCT (K) and Duv.
CctDuvResult compute_cct_duv_from_xyz(double X, double Y, double Z,
                                      const PlanckianLut &lut,
                                      const CctOptions &options = {});

} // namespace tm30
