#pragma once

/// @file cct.hpp
/// Correlated Color Temperature (CCT) and Duv via Ohno 2014 method.
///
/// Implements the triangular search algorithm from:
///   Ohno, Y. "Practical Use and Calculation of CCT and Duv."
///   LEUKOS 10, no. 1 (2014): 47-55.
///
/// The Planckian locus is represented as a pre-computed lookup table
/// of (T, u, v) points in CIE 1960 UCS, generated by integrating
/// the Planckian radiator formula with the CIE 1931 2° CMFs.
///
/// TM-30-20 §3.3: CCT of the test source shall be calculated using
/// the CIE 1931 2° CMFs and the Ohno 2013 method.

#include <vector>
#include <string>

namespace tm30 {

/// Result of CCT/Duv computation.
struct CctDuvResult {
  double cct;  // Correlated Color Temperature (K)
  double duv;  // Signed distance from Planckian locus in CIE 1960 UCS
               // Positive = above (green/yellow), negative = below (pink/purple)
};

/// Pre-computed Planckian locus lookup table.
///
/// Contains (T, u, v) points on the Planckian locus in CIE 1960 UCS,
/// generated with the CIE 1931 2° standard colorimetric observer.
/// Points are ordered by increasing temperature.
struct PlanckianLut {
  std::vector<double> T;  // Temperatures (K), monotonically increasing
  std::vector<double> u;  // CIE 1960 UCS u coordinate
  std::vector<double> v;  // CIE 1960 UCS v coordinate
};

/// Load a Planckian locus LUT from a CSV file.
///
/// Expected CSV format: cct,u,v  (header row with those column names).
/// @throws std::runtime_error on file-not-found or parse failure.
PlanckianLut load_planckian_lut(const std::string& filepath);

/// Compute CCT and Duv from CIE 1960 UCS (u,v) chromaticity.
///
/// Uses the Ohno 2014 triangular + parabolic search algorithm.
/// The LUT must contain at least 3 points covering the expected
/// temperature range of the test source.
///
/// @param u_test  CIE 1960 UCS u coordinate of the test source.
/// @param v_test  CIE 1960 UCS v coordinate of the test source.
/// @param lut     Pre-computed Planckian locus LUT (CIE 1931 2° observer).
/// @return        CctDuvResult with CCT (K) and Duv.
CctDuvResult compute_cct_duv(double u_test, double v_test,
                             const PlanckianLut& lut);

/// Compute CCT and Duv from CIE 1931 2° XYZ tristimulus values.
///
/// Convenience overload that converts XYZ to (u,v) first.
///
/// @param X  CIE 1931 2° X tristimulus value.
/// @param Y  CIE 1931 2° Y tristimulus value.
/// @param Z  CIE 1931 2° Z tristimulus value.
/// @param lut Pre-computed Planckian locus LUT.
/// @return    CctDuvResult with CCT (K) and Duv.
CctDuvResult compute_cct_duv_from_xyz(double X, double Y, double Z,
                                      const PlanckianLut& lut);

}  // namespace tm30
