#!/usr/bin/env python3
"""
oracle_recompute_12.py -- Independent recomputation of the 12 stale test
literals identified in tests/slice_02_xyz_test.cpp, slice_03_cct_test.cpp,
and slice_05_ces_colorimetry_test.cpp.

Deliberately does NOT call any pytm30 C++ code, and does NOT require the
`colour` (colour-science) package to be installed -- it reads the already
colour-science-sourced CSV files in data/ directly and re-implements, from
scratch in plain numpy, the two algorithms needed:

  1. CCT/Duv via the Ohno (2014) triangular+parabolic LUT search against
     planckian_uv.csv (this is a straight, from-spec re-implementation of
     the same public-domain algorithm pytm30's src/tm30/cct.cpp implements
     -- it is independent in the sense that matters: it is driven purely by
     the CSV data on disk, not by pytm30's own computed output).
  2. Plain trapezoidal integration of SPD * CMF for source XYZ (X, Z),
     matching TM-30-20 Sec 3.2 Eq (1)-(4) exactly (also what
     src/tm30/xyz.cpp implements, and what the existing test comment
     already documents as the golden-value method: "Generated by
     trapezoidal integration of the same CSV data that is loaded in this
     test").

Run: python3 tools/oracle_recompute_12.py
"""
import os
import csv
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.normpath(os.path.join(HERE, "..", "data"))


def load_csv_cols(path):
    with open(path) as f:
        rows = list(csv.reader(f))
    return np.array([[float(x) for x in row] for row in rows[1:]])


# ---------------------------------------------------------------------------
# CCT/Duv oracle (exact port of src/tm30/cct.cpp's Ohno LUT search)
# ---------------------------------------------------------------------------

_LUT = load_csv_cols(os.path.join(DATA, "planckian_uv.csv"))
_LUT_T, _LUT_U, _LUT_V = _LUT[:, 0], _LUT[:, 1], _LUT[:, 2]

_CMF2 = load_csv_cols(os.path.join(DATA, "cie_1931_2.csv"))
_CMF2_WL, _CMF2_X, _CMF2_Y, _CMF2_Z = _CMF2[:, 0], _CMF2[:, 1], _CMF2[:, 2], _CMF2[:, 3]


def xyz_to_uv(X, Y, Z):
    d = X + 15.0 * Y + 3.0 * Z
    return 4.0 * X / d, 6.0 * Y / d


def compute_cct_duv(u_test, v_test):
    d2 = (u_test - _LUT_U) ** 2 + (v_test - _LUT_V) ** 2
    best_i = int(np.argmin(d2))
    n = len(_LUT_T)
    if best_i == 0:
        im1, i0, ip1 = 0, 1, 2
    elif best_i == n - 1:
        im1, i0, ip1 = n - 3, n - 2, n - 1
    else:
        im1, i0, ip1 = best_i - 1, best_i, best_i + 1

    Tm1, T0, Tp1 = _LUT_T[im1], _LUT_T[i0], _LUT_T[ip1]
    um1, u0, up1 = _LUT_U[im1], _LUT_U[i0], _LUT_U[ip1]
    vm1, v0, vp1 = _LUT_V[im1], _LUT_V[i0], _LUT_V[ip1]

    def dist(u, v):
        return np.hypot(u_test - u, v_test - v)

    dm1, d0, dp1 = dist(um1, vm1), dist(u0, v0), dist(up1, vp1)
    l = np.hypot(up1 - um1, vp1 - vm1)
    x = (dm1 * dm1 - dp1 * dp1 + l * l) / (2.0 * l)
    x = min(max(x, 0.0), l)
    T_tri = Tm1 + (Tp1 - Tm1) * (x / l)
    uch = um1 + (up1 - um1) * (x / l)
    vch = vm1 + (vp1 - vm1) * (x / l)
    duv_mag = np.hypot(u_test - uch, v_test - vch)
    sign = 1.0 if v_test >= vch else -1.0
    duv_tri = duv_mag * sign

    denom = (Tp1 - T0) * (Tm1 - Tp1) * (T0 - Tm1)
    if abs(denom) < 1e-30:
        denom = 1e-30
    a = (Tm1 * (dp1 - d0) + T0 * (dm1 - dp1) + Tp1 * (d0 - dm1)) / denom
    b = -(Tm1 ** 2 * (dp1 - d0) + T0 ** 2 * (dm1 - dp1) + Tp1 ** 2 * (d0 - dm1)) / denom
    c = -(dm1 * (Tp1 - T0) * Tp1 * T0 + d0 * (Tm1 - Tp1) * Tm1 * Tp1 +
          dp1 * (T0 - Tm1) * T0 * Tm1) / denom

    if abs(a) > 1e-30:
        T_par = -b / (2.0 * a)
        T_par = min(max(T_par, Tm1), Tp1)
    else:
        T_par = T_tri

    duv_par_mag = a * T_par * T_par + b * T_par + c
    duv_par = duv_par_mag * sign

    duv_threshold = 0.002
    duv_abs = abs(duv_tri)
    T_tri_shift = T_tri + (T_par - T_tri) * min(duv_abs / duv_threshold, 1.0)

    if duv_abs < duv_threshold:
        return T_tri_shift, duv_tri
    return T_par, duv_par


def compute_cct_duv_for_spd_file(filename):
    """Loads a 2-column (wavelength, value) SPD csv from data/, computes XYZ
    via the CIE 1931 2-degree observer (cie_1931_2.csv) using plain
    trapezoidal integration, then CCT/Duv via the Ohno LUT search above."""
    sd = load_csv_cols(os.path.join(DATA, filename))
    wl, vals = sd[:, 0], sd[:, 1]

    # cie_1931_2.csv is 380-780 @ 1nm, same grid as the fl*_1nm.csv files --
    # exact index alignment (searchsorted), no interpolation needed/performed.
    idx = np.searchsorted(_CMF2_WL, wl)
    assert np.allclose(_CMF2_WL[idx], wl), "wavelength grids must align exactly"
    xb, yb, zb = _CMF2_X[idx], _CMF2_Y[idx], _CMF2_Z[idx]

    X = np.trapezoid(vals * xb, wl)
    Y = np.trapezoid(vals * yb, wl)
    Z = np.trapezoid(vals * zb, wl)
    u, v = xyz_to_uv(X, Y, Z)
    return compute_cct_duv(u, v)


# ---------------------------------------------------------------------------
# D65 source XYZ oracle (TM-30-20 Sec 3.2 Eq (1)-(4), CIE 1964 10-degree obs)
# ---------------------------------------------------------------------------

def compute_d65_source_xyz():
    d65 = load_csv_cols(os.path.join(DATA, "d65_1nm.csv"))
    wl, vals = d65[:, 0], d65[:, 1]
    assert len(wl) == 401, f"expected 401 points, got {len(wl)}"

    cmf10 = load_csv_cols(os.path.join(DATA, "cmf_1964_10.csv"))
    cmf_wl, xb_full, yb_full, zb_full = cmf10[:, 0], cmf10[:, 1], cmf10[:, 2], cmf10[:, 3]

    # cmf_1964_10.csv is 360-830 @ 1nm; trim (exact index match, no interp)
    # to the SPD's 380-780 domain, exactly like resample_cmf()/lerp_vector()
    # do in src/tm30/resample.cpp for coincident grid points.
    idx = np.searchsorted(cmf_wl, wl)
    assert np.allclose(cmf_wl[idx], wl), "wavelength grids must align exactly"
    xb, yb, zb = xb_full[idx], yb_full[idx], zb_full[idx]

    integral_st_ybar = np.trapezoid(vals * yb, wl)
    k = 100.0 / integral_st_ybar
    X = k * np.trapezoid(vals * xb, wl)
    Y = k * np.trapezoid(vals * yb, wl)
    Z = k * np.trapezoid(vals * zb, wl)
    return X, Y, Z


if __name__ == "__main__":
    print("=== CCT/Duv oracle recompute (FL1-FL12), from data/fl*_1nm.csv ===")
    fl_results = {}
    for i in range(1, 13):
        cct, duv = compute_cct_duv_for_spd_file(f"fl{i}_1nm.csv")
        fl_results[i] = (cct, duv)
        print(f"  FL{i:<2d}: CCT={cct:.10f}  Duv={duv:.10f}")

    print("\n=== D65 source XYZ oracle recompute, from data/d65_1nm.csv ===")
    X, Y, Z = compute_d65_source_xyz()
    print(f"  X={X:.10f}  Y={Y:.10f}  Z={Z:.10f}")

    print("\n=== Formatted for test-file literals ===")
    old = {
        1: (6428.2250, 0.00712681),
        2: (4224.5351, 0.00178952),
        3: (3446.0843, 0.00066824),
        4: (2937.9942, -0.00081817),
        5: (6345.2949, 0.01074928),
        6: (4148.5314, 0.00603795),
        7: (6494.7921, 0.00321985),
        8: (4997.2416, 0.00320913),
        9: (4149.0222, -0.00000651),
        10: (4998.3712, 0.00328524),
        11: (3998.6524, 0.00005033),
        12: (2999.6563, 0.00004406),
    }
    for i in range(1, 13):
        new_cct, new_duv = fl_results[i]
        old_cct, old_duv = old[i]
        d_cct = new_cct - old_cct
        d_duv = new_duv - old_duv
        flag = "CHANGED>TOL" if abs(d_cct) > 0.5 or abs(d_duv) > 5e-4 else "same/within tol"
        print(f"  FL{i:<2d}: old_cct={old_cct:.4f} new_cct={new_cct:.4f} "
              f"(d={d_cct:+.4f})   old_duv={old_duv:.8f} new_duv={new_duv:.8f} "
              f"(d={d_duv:+.8f})   [{flag}]")
